-- Reading Companion — library schema, Postgres.
--
-- The paragraph (a row in `blocks`) is the atomic unit of this application.
-- The study method operates on paragraphs, so everything upstream (OCR) exists
-- to produce clean blocks and everything downstream (summaries, critiques,
-- lookups) hangs off them.
--
-- Ported from the original SQLite schema. Three differences worth naming:
-- integer flags are real BOOLEANs, timestamps are TIMESTAMPTZ rather than
-- strings, and `books.last_page_id` is added by ALTER at the end because
-- Postgres will not accept a reference to a table that does not exist yet.

-- Identity, and the boundary of every access check in the application.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stored lowercased; the unique index below is what actually enforces
    -- that two people cannot register the same address in different case.
    email         TEXT        NOT NULL,
    display_name  TEXT        NOT NULL DEFAULT '',
    -- argon2id, encoded in PHC string format, which carries its own salt and
    -- parameters so they can be raised later without invalidating old hashes.
    password_hash TEXT        NOT NULL,
    -- Only an administrator may change the Ollama address. A normal user who
    -- could set it would be choosing a URL the *server* then makes requests
    -- to, which is server-side request forgery with extra steps.
    is_admin      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_users_email ON users (lower(email));

-- Opaque bearer tokens, stored hashed.
--
-- A read of this table must not yield working credentials, so what is kept is
-- SHA-256 of the token rather than the token. SHA-256 rather than argon2 here
-- deliberately: the token is 256 bits of CSPRNG output with no guessable
-- structure, so there is nothing for a slow hash to defend against, and this
-- runs on every single request.
CREATE TABLE sessions (
    token_hash BYTEA       PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Free-text, for showing someone their active sessions.
    label      TEXT        NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sessions_user    ON sessions (user_id);
CREATE INDEX idx_sessions_expires ON sessions (expires_at);

CREATE TABLE books (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Every access check in the application resolves to this column. Nothing
    -- below carries a user_id of its own: ownership is reached by joining up
    -- to here, so there is exactly one place it can be got wrong.
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       TEXT        NOT NULL,
    author      TEXT,
    -- Drives dictionary corpus, archaic normalisation, and coach calibration.
    -- One of: modern | early_20c | victorian | early_modern
    era         TEXT        NOT NULL DEFAULT 'modern',
    -- 'auto' derives the corpus from `era`; an explicit value overrides it.
    dict_corpus TEXT        NOT NULL DEFAULT 'auto',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_books_user ON books (user_id, updated_at DESC);

-- `page_no` is what the model read off the page, not the order you happened to
-- import in. It stays null until the page has been transcribed, and carries no
-- uniqueness constraint: two photographs genuinely can show the same numbered
-- page, and the honest way to catch that is the image hash below.
CREATE TABLE pages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id        BIGINT      NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    page_no        BIGINT,
    page_no_source TEXT        NOT NULL DEFAULT 'unknown',  -- detected|manual|unknown
    image_hash     TEXT,                   -- SHA-256 of the archival image
    -- photo | epub | pdf | web. Text sources skip OCR entirely: their words
    -- are already words, and a vision model would be slower and worse.
    source_kind    TEXT        NOT NULL DEFAULT 'photo',
    source_ref     TEXT,                   -- chapter label, URL, or similar
    -- For a photograph, the viewable full-resolution copy. For a text source,
    -- the file or address the page was taken from.
    image_orig     TEXT        NOT NULL,
    image_proc     TEXT,                   -- bounded copy actually sent to the model
    ocr_status     TEXT        NOT NULL DEFAULT 'pending',  -- pending|running|done|failed
    ocr_model      TEXT,                   -- which model produced ocr_raw
    ocr_raw        TEXT,                   -- verbatim model output, kept for re-segmentation
    ocr_error      TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- `ocr_raw` is retained deliberately: segmentation rules will improve, and we
-- want to re-derive blocks without re-running the model over the image.
CREATE TABLE blocks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id     BIGINT  NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
    ordinal     INTEGER NOT NULL,
    kind        TEXT    NOT NULL DEFAULT 'paragraph',  -- paragraph|heading|quote|footnote|caption
    -- text_raw  = diplomatic transcription, as printed (long-s, ligatures intact)
    -- text_norm = modernised reading text
    -- Both are stored so old books can be toggled without re-running OCR.
    text_raw    TEXT    NOT NULL,
    text_norm   TEXT    NOT NULL,
    user_edited BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (page_id, ordinal)
);

CREATE TABLE summaries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id         BIGINT      NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
    -- Which sentence of the paragraph this summarises. Null means the summary
    -- is of the paragraph as a whole. The reader works sentence by sentence
    -- first, then compresses the paragraph.
    sentence_ordinal INTEGER,
    sentence         TEXT        NOT NULL,
    revision         INTEGER     NOT NULL DEFAULT 1,
    -- the user's own who/what gate, passed before the model is ever consulted
    self_checked     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The coach's assessment, stored as the rubric the model actually returns.
--
-- Note the absence of any free-text column holding the paragraph's meaning.
-- The model emits categorical judgements only; the reader-facing wording is
-- composed by the application from these flags. See coach/mod.rs for why
-- prose feedback had to be abandoned.
CREATE TABLE critiques (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_id        BIGINT      NOT NULL REFERENCES summaries(id) ON DELETE CASCADE,
    verdict           TEXT        NOT NULL,  -- on_target|partial|off_target
    covers_subject    BOOLEAN     NOT NULL DEFAULT FALSE,
    covers_action     BOOLEAN     NOT NULL DEFAULT FALSE,
    covers_reason     BOOLEAN     NOT NULL DEFAULT FALSE,
    problem           TEXT        NOT NULL DEFAULT 'none',
    steering_question TEXT,                  -- scrubbed before storage
    model             TEXT        NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The "build up" step: paragraph sentences roll into sections, sections into
-- chapters. source_ids holds the ordered ids of whatever was rolled up —
-- a real array here rather than the JSON string SQLite forced.
CREATE TABLE rollups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT      NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    scope      TEXT        NOT NULL,  -- section|chapter
    label      TEXT,
    source_ids BIGINT[]    NOT NULL DEFAULT '{}',
    sentence   TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE lookups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT      REFERENCES books(id)  ON DELETE CASCADE,
    block_id   BIGINT      REFERENCES blocks(id) ON DELETE SET NULL,
    word       TEXT        NOT NULL,   -- surface form as printed
    lemma      TEXT,                   -- resolved headword
    sentence   TEXT,                   -- the sentence it was found in
    sense_json JSONB,                  -- candidate senses retrieved from dict.sqlite
    llm_gloss  TEXT,                   -- in-context paraphrase, if requested
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vocab (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id         BIGINT  REFERENCES books(id)   ON DELETE CASCADE,
    word            TEXT    NOT NULL,
    lemma           TEXT,
    count           INTEGER NOT NULL DEFAULT 1,
    first_lookup_id BIGINT  REFERENCES lookups(id) ON DELETE SET NULL,
    UNIQUE (book_id, word)
);

-- Server-wide configuration: the Ollama address, model choices, keep-alive.
-- Not per-user, because these describe the machine doing the inference rather
-- than anyone's preferences, and because letting an arbitrary account point
-- the server at a URL of their choosing is an SSRF hole. Admin-only.
CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Where the reader stopped. Added here rather than inline because it points
-- forward at `pages`. SET NULL rather than CASCADE: deleting the page they
-- happened to be on must not delete the book.
ALTER TABLE books
    ADD COLUMN last_page_id BIGINT REFERENCES pages(id) ON DELETE SET NULL;

CREATE INDEX idx_pages_book        ON pages (book_id, page_no);
-- Re-importing the same photograph is caught here rather than by page number.
CREATE UNIQUE INDEX idx_pages_hash ON pages (book_id, image_hash);
CREATE INDEX idx_blocks_page       ON blocks (page_id, ordinal);
CREATE INDEX idx_summaries_block   ON summaries (block_id, revision);
CREATE INDEX idx_critiques_summ    ON critiques (summary_id);
CREATE INDEX idx_lookups_book      ON lookups (book_id, created_at);
CREATE INDEX idx_rollups_book      ON rollups (book_id, scope);
